examples/configurations/demo-forge-nexus.yml
examples/notebooks/nexus-demo/00 - Nexus_Project_Initialisation.ipynb
examples/notebooks/nexus-demo/02 - Datasets.ipynb
examples/notebooks/nexus-demo/03 - Storing.ipynb
examples/notebooks/nexus-demo/04 - Querying.ipynb
examples/notebooks/nexus-demo/05 - Versioning.ipynb
examples/notebooks/nexus-demo/06 - JSON IO.ipynb
examples/notebooks/nexus-demo/07 - DataFrame IO.ipynb
examples/notebooks/nexus-demo/08 - Formatting.ipynb
examples/notebooks/nexus-demo/09 - Resolving.ipynb
examples/notebooks/nexus-demo/10 - Reshaping.ipynb
examples/notebooks/nexus-demo/11 - Modeling.ipynb
examples/notebooks/nexus-demo/12 - Mapping.ipynb
examples/notebooks/nexus-demo/13 - JSON-LD IO.ipynb
examples/notebooks/nexus-demo/14 - RDF IO.ipynb
examples/notebooks/nexus-demo/15 - SQL IO.ipynb
examples/notebooks/nexus-demo/16 - Debugging.ipynb
examples/notebooks/nexus-demo/neuroshapes_context.json

Updated nexus demo examples to run on the sandbox

---

examples/notebooks/nexus-demo/00 - Nexus_Project_Initialisation.ipynb
examples/notebooks/nexus-demo/01 - Resources.ipynb
examples/notebooks/nexus-demo/02 - Datasets.ipynb
examples/notebooks/nexus-demo/03 - Storing.ipynb
examples/notebooks/nexus-demo/04 - Querying.ipynb
examples/notebooks/nexus-demo/05 - Versioning.ipynb
examples/notebooks/nexus-demo/06 - JSON IO.ipynb
examples/notebooks/nexus-demo/07 - DataFrame IO.ipynb
examples/notebooks/nexus-demo/08 - Formatting.ipynb
examples/notebooks/nexus-demo/09 - Resolving.ipynb
examples/notebooks/nexus-demo/10 - Reshaping.ipynb
examples/notebooks/nexus-demo/11 - Modeling.ipynb
examples/notebooks/nexus-demo/12 - Mapping.ipynb
examples/notebooks/nexus-demo/13 - JSON-LD IO.ipynb
examples/notebooks/nexus-demo/14 - RDF IO.ipynb
examples/notebooks/nexus-demo/15 - SQL IO.ipynb
examples/notebooks/nexus-demo/16 - Debugging.ipynb

Change-Id: I4516c427c658374dc1aef872c08ace0ab156bf8c

Added Neuroshapes SHACL clone in Nexus examples

---

kgforge/specializations/stores/nexus/service.py

Used loop.create_task for Python 3.6

---

examples/notebooks/nexus-demo/00 - Nexus_Project_Initialisation.ipynb
examples/notebooks/nexus-demo/01 - Resources.ipynb
examples/notebooks/nexus-demo/02 - Datasets.ipynb
examples/notebooks/nexus-demo/03 - Storing.ipynb
examples/notebooks/nexus-demo/04 - Querying.ipynb
examples/notebooks/nexus-demo/05 - Versioning.ipynb
examples/notebooks/nexus-demo/06 - JSON IO.ipynb
examples/notebooks/nexus-demo/07 - DataFrame IO.ipynb
examples/notebooks/nexus-demo/08 - Formatting.ipynb
examples/notebooks/nexus-demo/09 - Resolving.ipynb
examples/notebooks/nexus-demo/10 - Reshaping.ipynb
examples/notebooks/nexus-demo/11 - Modeling.ipynb
examples/notebooks/nexus-demo/12 - Mapping.ipynb
examples/notebooks/nexus-demo/13 - JSON-LD IO.ipynb
examples/notebooks/nexus-demo/14 - RDF IO.ipynb
examples/notebooks/nexus-demo/15 - SQL IO.ipynb
examples/notebooks/nexus-demo/16 - Debugging.ipynb

Change-Id: I7bc117a7ec37fcfa36a8bfb16a79dc9bba626b5a

Updated link towards Nexus_Project_Initialisation.ipynb

---

examples/notebooks/nexus-demo/neuroshapes_context.json

Make the nexus-demo/04 - Querying.ipynb notebook running by partially addressing #25

Updated the example context from array to dict

---

examples/notebooks/getting-started/00 - Initialization.ipynb

Reuse endpoint value in Store configuration

---

.gitignore
examples/notebooks/getting-started/00 - Initialization.ipynb
examples/notebooks/getting-started/02 - Datasets.ipynb
examples/notebooks/getting-started/04 - Querying.ipynb
examples/notebooks/getting-started/05 - Versioning.ipynb
examples/notebooks/getting-started/07 - DataFrame IO.ipynb
examples/notebooks/getting-started/10 - Reshaping.ipynb
examples/notebooks/getting-started/11 - Modeling.ipynb
examples/notebooks/getting-started/12 - Mapping.ipynb
examples/notebooks/getting-started/13 - JSON-LD IO.ipynb
examples/notebooks/getting-started/16 - Debugging.ipynb
tests/specializations/models/data.py
tests/specializations/models/test_rdf_model.py

As part of fixing the tests which are failing, I am running the notebooks with both the example DemoModel + DemoStore and Neuroshapes + Nexus configurations.
I have added notes on what runs with what Model and what Store in the notebooks.
I have fixed some divergences existing when using one or the other example configuration.

Add notes in notebooks on what runs with what (Model / Store)

---

kgforge/specializations/models/rdf/service.py
tests/specializations/models/data.py

Adapted template test data to align with changes introduced in 95f69860bb39df8a749605da56665c9d108089b8
- model._template(type_, False) output 'id' when nodeeKind:IRI is enforced in the SHACL shape
- Templates are nested when a property shape has a 'sh:node' constraint or a type for which a shape was defined
Change-Id: I78df27b3c9c85ab234c5ecd9b3842ea1899348d9

Adapted template test data

---

examples/notebooks/getting-started/00 - Initialization.ipynb
examples/notebooks/use-cases/prod-forge-nexus.yml
kgforge/core/archetypes/store.py
kgforge/core/forge.py
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/demo_store.py
kgforge/specializations/stores/nexus/service.py
setup.py

Added Search endpoints configuration

---

kgforge/specializations/stores/nexus/service.py

Fixed File retrieve support

---

kgforge/specializations/resolvers/ontology_resolver.py

Fixed resolving to return ontology terms when notation and prefLabel are missing

---

examples/notebooks/use-cases/prod-forge-nexus.yml

* removed dash in front of `sparql`

Updated prod-forge-nexus.yml

---

kgforge/specializations/stores/nexus/service.py

Updated service.py to fix file retrieval support

---

kgforge/core/commons/files.py
kgforge/core/forge.py

Added support for loading a forge config from URL

---

docs/source/interaction.rst
docs/source/releases/v0.5.0-release-notes.rst
examples/notebooks/getting-started/14 - RDF IO.ipynb
kgforge/core/conversions/rdf.py
kgforge/core/forge.py
setup.py
tests/core/conversions/test_rdf.py
tests/data/shacl-model/context.json

The conversion can be controlled by:
* types
* a JSON-LD Frame
Updated the "14 - RDF IO notebook" notebook to document this feature

Added rdflib.Graph to Resource conversion

---

kgforge/core/archetypes/store.py
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/nexus/service.py

* Ignored prefix when rewriting SPARQL query

Added self referenced JSON-LD context support for BlueBrainNexus store

---

kgforge/core/archetypes/resolver.py
kgforge/core/archetypes/store.py
kgforge/core/forge.py
kgforge/specializations/resolvers/agent_resolver.py
kgforge/specializations/resolvers/demo_resolver.py
kgforge/specializations/resolvers/entity_linking/__init__.py
kgforge/specializations/resolvers/entity_linking/entity_linker.py
kgforge/specializations/resolvers/entity_linking/entity_linker_elasticsearch.py
kgforge/specializations/resolvers/entity_linking/service/__init__.py
kgforge/specializations/resolvers/entity_linking/service/entity_linker_elasticsearch_service.py
kgforge/specializations/resolvers/entity_linking/service/entity_linker_service.py
kgforge/specializations/resolvers/ontology_resolver.py
kgforge/specializations/resources/entity_linking_candidate.py

* Added EntityLinker base class with a generic implementation of _resolve()
* Added EntityLinkerElasticSearch, a specialization of EntityLinker
based on an encoder service for candidates generation and an elasticsearch endpoint for similarity computation using dense vectors
* Added support for elasticsearch query in Store and BlueBrainNexus store
* Added support for resolving a list of text not just str

Added Entity Linking as a specialization of resolving

---

kgforge/core/archetypes/store.py
kgforge/specializations/stores/bluebrain_nexus.py
tests/core/archetypes/test_store.py
tests/specializations/stores/test_bluebrain_nexus.py

Wrapped search generated SPARQL queries in Graph

---

examples/notebooks/getting-started/00 - Initialization.ipynb
examples/notebooks/use-cases/prod-forge-nexus.yml
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/nexus/service.py

Set asyncio max_connection value in BlueBrainNexus store's configuration

---

kgforge/core/archetypes/store.py
kgforge/core/forge.py
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/nexus/service.py
tests/core/archetypes/test_store.py

* an argument cross_bucket:bool can be set when calling forge.download()

Added cross_bucket download for BlueBrainNexus store:

---

kgforge/specializations/stores/nexus/service.py

Fixed typo in kgforge/specializations/stores/nexus/service.py

---

examples/notebooks/use-cases/MOOC_Content_based_Recommender_System_using_Blue_Brain_Nexus.ipynb
examples/notebooks/use-cases/dataset_from_different_sources.ipynb
examples/notebooks/use-cases/mappings/allen_ephys_dataset.hjson
examples/notebooks/use-cases/mappings/allen_morphology_dataset.hjson
examples/notebooks/use-cases/one_cell_minds.ipynb

* Added MOOC_Content_based_Recommender_System_using_Blue_Brain_Nexus.ipynb notebook
* Included "derivation" object in AIBS mappings: mappings/allen_ephys_dataset.hjson and mappings/allen_morphology_dataset.hjson

Added MOOC_Content_based_Recommender_System_using_Blue_Brain_Neuxs notebook

---

examples/notebooks/use-cases/MOOC_Content_based_Recommender_System_using_Blue_Brain_Nexus.ipynb
examples/notebooks/use-cases/dataset_from_different_sources.ipynb
examples/notebooks/use-cases/one_cell_minds.ipynb

Updated the three MOOC notebooks to their latest version.

Updated MOOC notebooks to latest version

---

kgforge/specializations/stores/bluebrain_nexus.py

Fixed ignored url fragment when retrieving a resource from BlueBrainNexus store

---

kgforge/core/archetypes/store.py
tests/conftest.py
tests/core/archetypes/test_store.py
tests/data/shacl-model/context.json

* context.has_vocab() true is no longer required to rewrite
* Raised QueryingError when an unknown term and no @vocab are provided

Updated SPARQL query rewriting

---

examples/notebooks/use-cases/prod-forge-nexus.yml
kgforge/specializations/models/rdf/store_service.py
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/nexus/service.py

Introduced bucket cached metadata context for BlueBrainNexus store

---

kgforge/specializations/stores/nexus/service.py

Used recursive context resolving when initialising BlueBrainNexus store

---

kgforge/core/conversions/rdf.py
tests/core/conversions/test_rdf.py
tests/data/shacl-model/context.json

Added a fix list of JSONLD keys to JSONify (i.e. to remove the '@' from)

---

kgforge/core/forge.py

Added Docstring to forge.py

---

kgforge/core/conversions/rdf.py

…a resource self referenced itself

Set framing @embed to True to avoid hitting max recursion error when a resource self referenced itself

---

docs/source/interaction.rst
examples/notebooks/getting-started/04 - Querying.ipynb
kgforge/core/archetypes/store.py
kgforge/core/commons/__init__.py
kgforge/core/commons/es_query_builder.py
kgforge/core/commons/parser.py
kgforge/core/forge.py
kgforge/specializations/stores/bluebrain_nexus.py
tests/core/archetypes/test_store.py
tests/specializations/stores/test_bluebrain_nexus.py

* Added for filtering (except when a PathWrapper is used) by store_metadata properties fixes #209
* Added support for datetime filtering
* Added support for disabling SPARQL rewriting when a correct SPARQL is provided fixes #218
* Fixes #189. limit/offset arguments supersede in query limit/offset

Updated SPARQL support

---

examples/notebooks/use-cases/prod-forge-nexus.yml

Added searchendpoints config in resolvers

---

examples/notebooks/getting-started/04 - Querying.ipynb
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/nexus/service.py

BlueBrainNexus store: added id and forge model jsonld context to ES search results

---

examples/notebooks/use-cases/prod-forge-nexus.yml

Reduced number of max connections in the configuration to prevent ServerDisconnect error

Reduced number of max connections

---

kgforge/specializations/models/rdf_model.py

Add info in ValueError message to ease debugging.

Improve ValueError message

---

examples/notebooks/getting-started/00 - Initialization.ipynb

A change in the order of the RDF model examples that ensures that the last one saved works with the next tutorials.

Reorganize tutorial 00

---

kgforge/core/resource.py
kgforge/specializations/models/rdf/directory_service.py
kgforge/specializations/stores/nexus/service.py
tests/core/resource.feature
tests/core/test_resource.py

Related to https://github.com/BlueBrain/nexus-forge/issues/211
The behavior was fixed, as shown bellow:

Fixing nested synchronization

---

examples/notebooks/getting-started/09 - Resolving.ipynb
kgforge/core/commons/strategies.py
kgforge/specializations/resolvers/agent_resolver.py
kgforge/specializations/resolvers/demo_resolver.py
kgforge/specializations/resolvers/ontology_resolver.py

Added strategy to match exactly but with case-insensitive regex.

Added EXACT_CASEINSENSITIVE_MATCH resolving strategy

---

examples/notebooks/getting-started/00 - Initialization.ipynb
examples/notebooks/getting-started/09 - Resolving.ipynb
examples/notebooks/use-cases/ResolvingStrategies.ipynb
kgforge/core/archetypes/resolver.py
kgforge/specializations/resolvers/agent_resolver.py
kgforge/specializations/resolvers/ontology_resolver.py
tests/core/test_resolving.py
tests/data/demo-resolver/cell_types.json

Related to https://github.com/BlueBrain/nexus-forge/issues/276
Added some changes to detect special characters and account them in the the Filter regex SPARQL query.

Improved case-insensitive match to account for special characters.

---

kgforge/core/resource.py
tests/core/test_resource.py

In the initial fix, only resources were checked. Now also lists of resources are inspected.

Accounting for lists in the inner synchronization

---

kgentitylinkingsklearn/entity_linking_sklearn.py
kgforge/specializations/resolvers/agent_resolver.py
kgforge/specializations/resolvers/entity_linking/entity_linker_elastic.py

Fixed wrong access of targetsbucket in kgentitylinkingsklearn/entity_linking_sklearn

---

examples/configurations/nexus-resolver/term-to-resource-mapping.hjson
kgforge/specializations/resolvers/ontology_resolver.py

The simplest solution to @lecriste's needs.
I did not go for a "costume" creation of the template, as last time when I did it was discarded.

Add extra field to the ontology resolver template and mapping.

---

examples/mappings/DemoDB/mappings/DictionaryMappings/Example.hjson
examples/mappings/LICENSE
examples/mappings/MouseLight/mappings/DictionaryMapping/NeuronMorphology.hjson
examples/mappings/MouseLight/metadata.json
examples/mappings/NeuroMorpho/jsonld_context.json
examples/mappings/NeuroMorpho/mappings/DictionaryMapping/NeuronMorphology.hjson
examples/mappings/NeuroMorpho/metadata.json
examples/mappings/README.md
examples/mappings/UniProt/jsonld_context.json
examples/mappings/UniProt/mappings/DictionaryMapping/Gene.hjson
examples/mappings/UniProt/mappings/DictionaryMapping/Protein.hjson
examples/mappings/UniProt/metadata.json
examples/mappings/allen-cell-types-database/mappings/DictionaryMapping/NeuronMorphology.hjson
examples/mappings/allen-cell-types-database/mappings/DictionaryMapping/PatchedCell.hjson
examples/mappings/allen-cell-types-database/mappings/DictionaryMapping/Subject.hjson
examples/mappings/scientists-database/DictionaryMapping/Association.hjson
examples/mappings/scientists-database/DictionaryMapping/Contribution.hjson

Added all folders from the PR #273 , a LICENSE and one sentence about the documentation.

Add mappings from PR #273

---

Contributing.rst

Added CLA requirement for external contributors.

Add CLA section to contributing documentation file.

---

kgforge/specializations/models/rdf/directory_service.py
kgforge/specializations/models/rdf/store_service.py
setup.py

Use the latest version of pyshacl, and replace object with newer method.

Upgrade pyshacl and replace Validator with validate function

---

kgforge/specializations/stores/demo_store.py

Adresses https://github.com/BlueBrain/nexus-forge/issues/346

add schema id missing parameter in _update_one of demo store

---

kgforge/core/archetypes/model.py

Some functions in the model archetype were returning an optional string, but for some cases in if statements there were no return statements

return None if pretty in model archetype

---

examples/notebooks/getting-started/04 - Querying.ipynb
kgforge/core/archetypes/read_only_store.py
kgforge/core/archetypes/store.py
kgforge/core/forge.py
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/demo_store.py

[DKE-1296](https://bbpteam.epfl.ch/project/issues/browse/DKE-1296)

return resources  as dictionaries when forge.elastic if as_resource = False

---

examples/notebooks/use-cases/prod-forge-nexus.yml

self explanatory...
it was the case a few commits ago

Use as default Aggregate SPARQL view

---

kgforge/core/conversions/dataframe.py
tests/core/conversions/test_dataframe.py

This new version, which stems from @ssssarah linking me to [this post](https://stackoverflow.com/questions/54776916/inverse-of-pandas-json-normalize), has a better time complexity.

improved deflatten function (lower time complexity)

---

examples/notebooks/use-cases/ResolvingStrategies.ipynb
examples/notebooks/use-cases/prod-forge-nexus.yml

resolve with target species returns only species and strain returns strains

Update prod-forge-nexus.yml for species vs strain resolving

---

kgforge/specializations/stores/bluebrain_nexus.py

Private method for file metadata retrieval

File fetch

---

examples/notebooks/use-cases/BBP KG Creating and Modifying Schemas.ipynb
kgforge/specializations/stores/bluebrain_nexus.py
kgforge/specializations/stores/nexus/prepare_methods.py
kgforge/specializations/stores/nexus/service.py
tests/specializations/stores/test_bluebrain_nexus.py

To address #414
Add a method to build the url checking if the schema_id is the SHACL schema.

Check for schema id to use schema endpoint

---

.github/workflows/publish.yml

See README from https://github.com/pypa/gh-action-pypi-publish

update pypi publish action version

---

AUTHORS.md
README.rst

Following what github says as contributors, just missing Pigueiras and alex4200, as I am not sure who they are.

Updated authors and copyright
