BlueBrain/nexus-forge

examples/notebooks/nexus-demo/04 - Querying.ipynb
Fixes #26 
p.type is a composed path containing p.type.id. p.type.id should be used for filtering.
=> Used leaf path p.type.id in Querying.ipynb

examples/notebooks/use-cases/BBP KG Search and Download.ipynb
Atlas section in BBP KG Search and Download.ipynb notebook was not using the forge_atlas session consistently.
Addresses issues raised in #36.
=> Fixed atlas section in notebook to use correct forge session

setup.py
See #43.
The actual fix is about what happens at: https://github.com/BlueBrain/nexus-forge/blob/1f1c47b661769f1f9ce871b804db98d680307de9/kgforge/specializations/models/rdf/service.py#L110.
=> Fix temporary the Shape.traverse() issue

examples/notebooks/getting-started/02 - Datasets.ipynb, kgforge/specializations/resources/datasets.py
Change of behaviour for `Dataset.add_files(...)`.
The **current** behaviour produces the following structure.
```
{
...
"hasPart": [
{
"@type": "DataDownload",
...
},
...
]
}
```
The **new** behaviour produces the following structure.
This introduces the new level `distribution`.
```
{
...
"hasPart": [
{
"distribution": {
"@type": "DataDownload",
...
}
},
...
]
}
```
=> Consider Dataset files as parts

.travis.yml
Attempt to fix the issue with Travis saying:
> Skipping a deployment with the pypi provider because this is not a tagged commit.
while the commit 906532b was tagged with `git tag -a v0.3.1 HEAD`.
=> Fix releasing on PyPI by Travis

docs/source/archetypes.rst, docs/source/interaction.rst, kgforge/core/archetypes/store.py, kgforge/core/forge.py, kgforge/specializations/stores/bluebrain_nexus.py, kgforge/specializations/stores/demo_store.py
```
resource = forge.retrieve(<resource_id>, cross_bucket=True)
```
When using `cross_bucket=True`, resources could be retrieved from other buckets.
If the configured `Store` bucket has the following Nexus Delta resolvers:
- an InProject resolver with priority 1,
- a CrossProject resolver to schemas and JSON-LD context with priority 2,
- a CrossProject resolver to other buckets with priority 3,
then, using `cross_bucket=True` will try to retrieve the resource with the given `@id`:
- firstly in the configured `Store` bucket,
- secondly amongst the schemas and JSON-LD context,
- thirdly in the other buckets.
=> Add cross-bucket retrieval feature

docs/source/archetypes.rst, docs/source/interaction.rst, kgforge/core/archetypes/store.py, kgforge/core/forge.py, kgforge/specializations/resources/datasets.py, kgforge/specializations/stores/bluebrain_nexus.py
Improvements when using `forge.download(...)` and `Dataset.download(...)`:
- If the given directory path doesn't exist and no URLs were found, the path is not created.
- When a file with the same file name is already existing, it is not overwritten.
The concerned downloaded file has a timestamp added as suffix.
Here is an example:
=> Prevent Store.download() to overwrite existing files

kgforge/specializations/stores/nexus/service.py
Hi,
I fixed the bug that appears from nesting event loops, when the current event loop does not exist. I am not sure it's the best solution, but now works for both Jupyter notebook and on the server side.
`asyncio.get_event_loop()` retrieves the current event loop and if it does not exists throws a `RuntimeError`, this corresponds to the case when we run the forge on the server-side.
=> Bugfix on nested_asyncio

kgforge/specializations/stores/bluebrain_nexus.py
Currently calling:
`forge.retrieve(id=https://..?rev=1)` will throw a RetrievalError with a 404 when using a configured Nexus Delta Store.
Also the query params (e.g rev=1) were not taken into account. The solution is to extract the query params out of the url and add them as values of the params argument in `requests.get(url, params=...)`. 
When the `version` argument is set (like in `forge.retrieve(id=https://..?rev=1&p=aparam, version=2)` ), then it should superseed the `rev` query param while the other query params (e.g `p=aparam`) should be kept as is.
=> Added query param support when retrieving a resource

examples/notebooks/getting-started/02 - Datasets.ipynb, kgforge/core/archetypes/store.py, kgforge/core/reshaping.py, kgforge/specializations/resources/datasets.py, tests/conftest.py, tests/core/archetypes/test_store.py, tests/core/test_reshaping.py, tests/specializations/resources/test_datasets.py
Fixes #84 
* Downloading no longer failing when one resource does not have the path to follow
* Downloading fails with DownloadingError when all resources do not have the path to follow
* Externalised forge config fixture to tests/conftest.py to modularise forge session creation during test
=> Fixed failing forge.download

docs/source/interaction.rst, kgforge/specializations/resources/datasets.py, tests/conftest.py, tests/core/archetypes/test_store.py, tests/core/conversions/conftest.py
Fixes #80 
* add_generation, add_derivation, add_invalidation, add_contribution are now all accepting a resource IRI or a Resource
* when providing an IRI, forge.freeze will fail as there is no way to know about which version to freeze with
=> Updated Dataset provenance setting:

kgforge/core/forge.py
`forge.resolve(...)` is often used within a mapping file to automatically resolve or link to a 'master' resource in a knowledge base for example.
```
{
type: x.type
id: x.id
property: forge.resolve(text, strategy=ResolvingStrategy.EXACT_MATCH)
}
```
But because `ResolvingStrategy` can't be imported during the mapping execution, an error will be thrown.
Allowing the user to provide string as the `ResolvingStrategy` name would address that.
=> Added setting resolving strategy using a string name

examples/notebooks/getting-started/04 - Querying.ipynb, kgforge/core/archetypes/store.py, kgforge/core/wrappings/paths.py, kgforge/specializations/stores/bluebrain_nexus.py, tests/core/wrappings/test_paths.py
A dictionary can be provided for filters in `forge.search(self, resolvers: Optional[List["Resolver"]], *filters, **params) -> List[Resource]`:
* {'key1': 'val', 'key2': {'key3': 'val'}} will be translated to:
- [Filter(operator='__eq__', path=['key1'], value='val'), Filter(operator='__eq__', path=['key2', 'key3'], value='val')]
* only the '==' operator is supported
* nested dict are supported
=> Added support for dict as filters in forge.search

kgforge/core/archetypes/store.py, kgforge/core/commons/context.py, kgforge/core/commons/files.py, kgforge/specializations/stores/bluebrain_nexus.py, tests/core/archetypes/test_store.py, tests/core/conversions/test_rdf.py, tests/specializations/stores/test_bluebrain_nexus.py
Added support for filtering using dict with type values or keys not defined in configured Model
* Added the configured context's @vocab as base SPARQL prefix if any
* Updated the query rewriting regex to prevent rewriting urls
* Added has_vocab function to Context
=> Added support for filtering with type values or keys not defined in configured Model

examples/configurations/nexus-store/publishing-file-to-resource-mapping.hjson
For dissemination data, the **distribution** object on resources should not include the store and location metadata. The _publishing-file-to-resource-mapping.hjson_ can be used for this use case (instead of to the file-to-resource-mapping.hjson file in the same directory)
=> Added file to resource mapping for publishing

setup.py
Fixed `RuntimeError: This event loop is already running` on batch operations executed in Jupyter (pinned `nest-asyncio>=1.5.1`).
The error happens, when there is a new version of `tornado` (>=5) and an old version of `nest-asyncio`, so there are two solutions:
- downgrade `tornado` to `4.X`,
- upgrade `nest-asyncio` to `1.5.X` (which is a better solution, in order not to depend on an outdated package)
=> Fixed asyncio issue with Jupyter

setup.py
`rdflib-jsonld` is deprecated and becomes a part of `rdflib==6.0.1`, installing `rdflib==6.0.1` creates a dependency conflict:
```
pyshacl 0.11.6.post1 requires rdflib<6.0.0,>=4.2.2, but you have rdflib 6.0.1 which is incompatible.
```
Due to the fixed version  `pyshacl==0.11.6.post1` in `setup.py`
This PR contains the following fix ():
- fixed `rdflib<6.0.0`
- fixed `rdflib-jsonld<=0.5.0`
=> Fixed rdflib and rdflib_jsonld versions

.travis.yml, kgforge/core/commons/context.py, kgforge/core/conversions/rdf.py, kgforge/specializations/models/rdf/service.py, setup.py
This commit is for catching up with the latest releases of pyshacl and rdflib.
* Removed rdflib-jsonld dependancy which is now part of rdflib from rdflib>=6.0.0
* Added a ShapeWrapper class extending pyshacl.shape to workaround added __slots__ preventing from dynamically adding methods
* Set min python version to v3.7 as required by pyshacl from 0.17.0
=> Upgraded to rdflib>=6.0.0 and pyshacl==v0.17.2:

examples/notebooks/use-cases/BBP KG Create Datasets.ipynb, examples/notebooks/use-cases/BBP KG Ontology Brain Building Workflow Search and Exploration.ipynb
1. Staging address of the `Create Datasets` was outdated, so it was changed to the correct endpoint address, which used in the other notebooks.
2. Updated to the fact that `nsg:about` is now just `about`.
3. The list of `usesCircuitWithProperty` can be called directly as a property.
=> Updated staging endpoint and resource property names.

setup.py
With the newer versions of rdflib we are encountering errors resolving the context given in the configuration.
=> Force rdflib 6.2.0 to avoid errors resolving context.

kgforge/core/archetypes/store.py, kgforge/core/conversions/rdf.py, kgforge/specializations/stores/bluebrain_nexus.py
In both retrieval and search, when building the resource object, if an exception is thrown, in the catching block a reference to the "resource" variable was made when its building was unsuccessful, so a variable is referenced before assignment. This would lead to an error that would shield the real error message from the exception from being propagated.
+ Addressing [this issue](https://github.com/BlueBrain/nexus-forge/issues/299), throwing a more explicit error of what went wrong. There was an assumption a string would be manipulated, but now a check on the type is being performed.
=> Not use resource object when resource object creation fails in retrieve, search

kgforge/specializations/resolvers/agent_resolver.py, kgforge/specializations/resolvers/store_service.py
This is related to this comment:
https://github.com/BlueBrain/nexus-forge/commit/051eb73d2091c2cecccdf54358f4980b8e876959#commitcomment-117123788
The ontology resolver was not updated when the filters were added, so it breaks when calling the function `get_context`
- Added filters to the call in the agent resolver
- changed the way that filters are defined to avoid KeyErrors
=> Added filters to agent resolver

examples/configurations/nexus-store/file-to-resource-mapping.hjson, examples/notebooks/getting-started/08 - Formatting.ipynb, kgforge/core/archetypes/store.py, kgforge/core/commons/formatter.py, kgforge/core/forge.py, kgforge/specializations/stores/bluebrain_nexus.py, kgforge/specializations/stores/demo_store.py, kgforge/specializations/stores/nexus/service.py, tests/specializations/stores/test_bluebrain_nexus.py
Related to [this issue](https://bbpteam.epfl.ch/project/issues/browse/BBPP134-536).
- Added methods to get a context from a store and from a model
- Added method to extend an URI using a given context
=> Added method to get context from model or store and another to expand the url using a context

kgforge/core/archetypes/resolver.py, kgforge/core/forge.py
=> Enabled resolvers mapping files to contains rules calling a forge method

kgforge/core/conversions/rdf.py, tests/core/conversions/test_rdf.py
rdflib.plugins.shared.jsonld.context.Context.resolve(iri) [return ""](https://github.com/RDFLib/rdflib/blob/f34c476ff099b39fe253430cdc25ebc121837e5e/rdflib/plugins/shared/jsonld/context.py#L323) when iri contains space. This leads to silently replacing an iri with "" in   [_remove_ld_keys](https://github.com/BlueBrain/nexus-forge/blob/a936ef152e82afaa1ca0fc019dc4b3f5f79cecae/kgforge/core/conversions/rdf.py#L471).
=> Raised an exception when a jsonld dict with an @id containing space character is provided to from_jsonld

kgforge/specializations/stores/bluebrain_nexus.py, kgforge/specializations/stores/nexus/service.py, tests/specializations/stores/test_bluebrain_nexus.py
* BlueBrainNexusStore: updating schemas required a specific schema URI to be present in the request URL or '_' in case of UNCONSTRAINED resources
=> BlueBrainNexusStore: fix updating schemas

examples/notebooks/use-cases/nsg-forge-nexus.yml
The existing configuration file does not work for the neurosciencegraph/datamodels as the bbp.neuroshapes.org context was deprecated in that project.
Added a configuration file `nsg-forge-nexus.yml` that can be use in that case.
=> Added project configuration for neurosciencegraph/datamodels

kgforge/specializations/stores/bluebrain_nexus.py, kgforge/specializations/stores/nexus/service.py
Extends [this MR](https://github.com/BlueBrain/nexus-forge/commit/02640967dd4034a4a4f5d566f322f2d9fdb9bd42), for the deprecation of schemas
=> Use prepare uri when deprecating resources

kgforge/core/commons/files.py, kgforge/core/forge.py, tests/specializations/stores/test_bluebrain_nexus.py
When running tests that initialise the BlueBrainNexus store, load store configuration from `./examples/notebooks/use-cases/prod-forge-nexus.yml`
=> Load local configuration when configuration tests

examples/configurations/nexus-resolver/term-to-resource-mapping.hjson, kgforge/specializations/resolvers/ontology_resolver.py
forge.resolve now returns resource.hasLeafRegionPart if available. This helps when resolving brain regions to check if a layer should be provided or not.
=> resolving returns also the hasleafregionpart attribute of the resource

kgforge/core/archetypes/model.py, kgforge/specializations/models/rdf/directory_service.py, kgforge/specializations/models/rdf_model.py, tests/specializations/models/test_rdf_directory_service.py
* forge.prefixes() was raising pandas.Dataframe error "if using all scalar values, you must pass an index"
* fixed forge.types() to properly collect types from rdfsercice.class_to_shape
* fixed forge.template() when using an rdf  model based on a store service: Unable to generate template:'tuple' object has no attribute 'traverse'
=> Fixed coupled of issues

examples/notebooks/use-cases/BBP KG Forge retrieval.ipynb, kgforge/core/commons/execution.py, kgforge/core/forge.py, kgforge/specializations/stores/bluebrain_nexus.py, kgforge/specializations/stores/nexus/service.py
1. Generic catching of http errors on requests now also catches the errors thrown by aiohttp
2. In the case of retrieval, there is more logic that goes into making requests (there may be a single request, just like there may be 3 of them)
- Therefore, a different task_creator is used (can be found in BlueBrainNexus)
- The entire logic of retrieval is located inside a co-routine (async-await block), see _retrieve.
- In the case of single resource retrieval, we force a blocking call.
- In the case of multiple resources retrieval, a different task_creator is provided to BatchRequest.batch_request, one that schedules tasks that are based on the asynchronous retrieval logic.
When multiple ids are provided, if some fail but not all, for the failed ones an Action object is returned, and a …
=> Batch retrieve

kgforge/core/forge.py, setup.py, tests/core/test_forge.py
To ensure the pyshacl environment variable is set when using `forge.validate`, I added a method to set it at initializing a `KnowledgeGraphForge` instance.
=> Add method when initializing forge to export pyshacl environment variable

kgforge/specializations/stores/bluebrain_nexus.py
This accounts also for the case where the path that was given contains the "full bucket path", with endpoint and so on.
Now it takes only the last values, as it was doing before the latest change.
=> Fix org and project metadata

kgforge/specializations/stores/bluebrain_nexus.py
For the sake of being able to rewrite the URI without having a forge instance tied to the appropriate bucket
=> rewrite uri as static method

kgforge/specializations/stores/bluebrain_nexus.py
For some reason this parameter was not passed to the prepare method.
=> Use `schema_id` in `prepare_update`

kgforge/core/archetypes/model.py, kgforge/specializations/models/demo_model.py, kgforge/specializations/models/rdf/service.py, kgforge/specializations/models/rdf/store_service.py, kgforge/specializations/models/rdf_model.py
- the traverse function being optionally overwritten on Shape was due to a change in pyshacl versions (I believe an old version had this version but a newer one no longer had it. For the version we have fixed, this function does not exist) https://github.com/BlueBrain/nexus-forge/issues/43 https://github.com/BlueBrain/nexus-forge/pull/44 
- renamed usage of `_transitive_load_shape_graph` to `_transitive_load_resource_graph`
- dummy implementation of `_validate_many` in `DemoModel`
- Override pyshacl `ShapesGraph` implementation of `def shapes` to return `list` instead of `dict_values()` so that it can be picklable (for multiprocessing)
- Parallelized validate. 
-> cannot use threads because pyshacl uses rdflib, rdflib uses pyparsing and it is not thread safe
-> shape loading occurs before …
=> Parallelize validate

kgforge/specializations/models/rdf/store_service.py, kgforge/specializations/models/rdf_model.py, kgforge/specializations/stores/bluebrain_nexus.py, kgforge/specializations/stores/nexus/batch_request_handler.py, setup.py
- 2 (main+metadata through resource endpoint) or 3 (main fail through resource endpoint, main+metadata through resolver endpoint) requests were necessary to retrieve resources:
- When using cross_bucket = False, the resource endpoint is used. There was an issue with the retrieval of the metadata with annotate = True. It has since then been fixed https://github.com/BlueBrain/nexus/issues/4737 
- When using cross_bucket = True, the resolvers endpoint is used. It was not possible to get metadata along with the data if retrieve_source = True, now it is, with the annotate=True query parameter. https://github.com/BlueBrain/nexus/issues/4717
- Remove async force complete for retrieval of one resource. Synchronous requests are now used, since the body of the function is simpler, a little bit of …
=> Simplify retrieve
